# Generated by Django 2.1.5 on 2019-01-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0001_initial'),
        ('list', '0003_auto_20190119_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lists',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lists.Lists'),
        ),
    ]
