# Generated by Django 2.1.5 on 2019-01-24 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('author', models.ForeignKey(default=None, on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
