# Generated by Django 2.1.5 on 2019-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
