# Generated by Django 2.1.5 on 2019-01-27 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lists', '0003_auto_20190127_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('todo_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(default=None, on_delete=True, to=settings.AUTH_USER_MODEL)),
                ('lists', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lists.Lists')),
            ],
        ),
    ]
