# Generated by Django 2.1.5 on 2019-03-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0006_auto_20190324_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
