# Generated by Django 2.1.5 on 2019-03-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0007_auto_20190328_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='slug',
        ),
    ]
