# Generated by Django 2.1.5 on 2019-03-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0008_auto_20190328_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='a'),
        ),
        migrations.AddField(
            model_name='lists',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
    ]
